In [1]:
import pandas as pd #more info at http://pandas.pydata.org/
import numpy as np #more info at http://www.numpy.org/
import matplotlib.pyplot as plt #some examples for you at http://matplotlib.org/gallery.html 
from matplotlib import gridspec #more info at http://matplotlib.org/api/gridspec_api.html
from scipy import stats
import seaborn as sns
from seaborn import pairplot

plt.style.use('ggplot') #For improving the visualization style (options: grayscale, bmh, dark_background, ggplot, and fivethirtyeight)

#Magic line: to show the plots inline in the Jupyter Notebook
%matplotlib inline

import warnings
warnings.filterwarnings('ignore') #To avoid showing annoying warns

In [2]:
import math
import random
import time
from keras_pandas.Automater import Automater

import tensorflow as tf
from tensorflow import keras
from keras.datasets import mnist
from tensorflow.keras import layers
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Input, Dense, Activation, ZeroPadding2D, BatchNormalization, Flatten, Conv2D, Conv1D, LSTM, Reshape
from tensorflow.keras.layers import AveragePooling2D, MaxPooling2D, Dropout, GlobalMaxPooling2D, GlobalAveragePooling2D
print(tf.__version__)

2.6.2

In [3]:
df = pd.read_csv('dataset-shortened-concatenated.txt', error_bad_lines=False, sep=';')
#df.drop()
df = df.drop(["frame.time_epoch", "ip.src", "ip.dst", "dns.qry.name", "tcp.flags"], axis=1)

protos = {
    '6': 6,
    '17': 17
}

df['ip.proto'] = df['ip.proto'].astype(str).apply(lambda x: x.split(",")[len(x.split(",")) - 1])
df['ip.proto'] = df['ip.proto'].astype(str).apply(lambda x: x.replace('.0',''))
df['ip.proto'] = df['ip.proto'].apply(lambda i: protos[i] if i in protos else i)
df['ip.proto'] = df['ip.proto'].astype(float)
df['frame.len'] = df['frame.len'].astype(float)
df = df.astype('float32')
df.dtypes
#df.dtypes()
# # Transform the data set, using keras_pandas
# categorical_vars = ['frame.len', 'ip.proto', 'tcp.flags']
# numerical_vars = ['udp.dstport', 'udp.srcport', 'tcp.dstport', 'tcp.srcport']
# text_vars = ['ip.src', 'ip.dst', 'dns.qry.name']

# auto = Automater(data_type_dict={"categorical": categorical_vars, "numerical": numerical_vars, "text": text_vars})
# auto.fit(df)
# X, y = auto.fit_transform(df)

frame.len      float32
ip.proto       float32
udp.dstport    float32
udp.srcport    float32
tcp.srcport    float32
tcp.dstport    float32
dtype: object

In [4]:
df

       frame.len  ip.proto  udp.dstport  udp.srcport  tcp.srcport  tcp.dstport
0         1490.0      17.0          NaN          NaN          NaN          NaN
1         1052.0      17.0          NaN          NaN          NaN          NaN
2         1490.0      17.0         22.0         53.0          NaN          NaN
3         1514.0      17.0          NaN          NaN          NaN          NaN
4         1514.0      17.0          NaN          NaN          NaN          NaN
5           60.0       6.0          NaN          NaN      50324.0         22.0
6           60.0       6.0          NaN          NaN      50324.0         22.0
7         1514.0      17.0          NaN          NaN          NaN          NaN
8           60.0       6.0          NaN          NaN        443.0      59688.0
9         1514.0      17.0          NaN          NaN          NaN          NaN
10         407.0       6.0          NaN          NaN        443.0      43520.0
11          60.0       6.0          NaN          NaN      50324.0         22.0
12        1490.0      17.0          NaN          NaN          NaN          NaN
13        1490.0      17.0          NaN          NaN          NaN          NaN
14        1052.0      17.0         22.0         53.0          NaN          NaN
15         659.0       6.0          NaN          NaN        443.0      43520.0
16        1514.0      17.0          NaN          NaN          NaN          NaN
17          60.0       6.0          NaN          NaN      42060.0       8791.0
18        1514.0      17.0          NaN          NaN          NaN          NaN
19          74.0       6.0          NaN          NaN      57468.0         80.0
20        1078.0       6.0          NaN          NaN        443.0      47540.0
21         518.0       6.0          NaN          NaN        443.0      47540.0
22          60.0       6.0          NaN          NaN        443.0      42960.0
23        1514.0      17.0          NaN          NaN          NaN          NaN
24         293.0       6.0          NaN          NaN        443.0      47540.0
25        1072.0       6.0          NaN          NaN        443.0      47540.0
26        1078.0       6.0          NaN          NaN        443.0      47540.0
27        1514.0      17.0          NaN          NaN          NaN          NaN
28        1514.0      17.0          NaN          NaN          NaN          NaN
29          60.0       6.0          NaN          NaN      29011.0       1024.0
...          ...       ...          ...          ...          ...          ...
68603     1336.0      17.0      20480.0      37318.0          NaN          NaN
68604     1336.0      17.0      20480.0      37318.0          NaN          NaN
68605     1336.0      17.0      20480.0      37318.0          NaN          NaN
68606     1336.0      17.0      20480.0      57731.0          NaN          NaN
68607     1336.0      17.0      20480.0      57731.0          NaN          NaN
68608     1336.0      17.0      20480.0      57731.0          NaN          NaN
68609     1336.0      17.0      20480.0      57731.0          NaN          NaN
68610     1336.0      17.0      20480.0      57540.0          NaN          NaN
68611     1336.0      17.0      20480.0      57540.0          NaN          NaN
68612     1336.0      17.0      20480.0      57540.0          NaN          NaN
68613     1336.0      17.0      20480.0      60297.0          NaN          NaN
68614     1336.0      17.0      20480.0      52081.0          NaN          NaN
68615     1336.0      17.0      20480.0      47860.0          NaN          NaN
68616     1336.0      17.0      20480.0      57731.0          NaN          NaN
68617     1336.0      17.0      20480.0      57731.0          NaN          NaN
68618     1336.0      17.0      20480.0      57731.0          NaN          NaN
68619     1336.0      17.0      20480.0      37318.0          NaN          NaN
68620     1336.0      17.0      20480.0      37318.0          NaN          NaN
68621      590.0      17.0      20480.0      57731.0          NaN          NaN
68622     1336.0      17.0      20480.0      37318.0          NaN          NaN
68623     1336.0      17.0      20480.0      37318.0          NaN          NaN
68624      590.0      17.0      20480.0      57731.0          NaN          NaN
68625      590.0      17.0      20480.0      57731.0          NaN          NaN
68626     1336.0      17.0      20480.0      37706.0          NaN          NaN
68627     1336.0      17.0      20480.0      37706.0          NaN          NaN
68628     1336.0      17.0      20480.0      37706.0          NaN          NaN
68629     1336.0      17.0      20480.0      37706.0          NaN          NaN
68630     1336.0      17.0      20480.0      57540.0          NaN          NaN
68631     1336.0      17.0      20480.0      57540.0          NaN          NaN
68632     1336.0      17.0      20480.0      57540.0          NaN          NaN

[68633 rows x 6 columns]

In [5]:
labels = []
with open('labels.txt') as f:
    for line in f:
        labels.append(line.replace("\n", "").replace(".pcapng", "").replace(".pcap", ""))

In [6]:
df.fillna(0, inplace=True)
tensor = tf.convert_to_tensor(df)
print(tensor[0])

tf.Tensor([1490.   17.    0.    0.    0.    0.], shape=(6,), dtype=float32)

In [7]:
newlabels = labels.copy();
newlabels.pop(0)
newlabels.pop(0)
newlabels.pop(0)
uniquelabels = list(set(newlabels))
print(uniquelabels)
labelcount = len(uniquelabels)
print("lc:" + str(labelcount))
#print(hash(newlabels[6000]) % labelcount)
tf.print(tensor[6000])
for i in range(len(newlabels)):
    for o in range(len(uniquelabels)):
        if uniquelabels[o] == newlabels[i]:
            newlabels[i] = o
#    newlabels[i] = hash(newlabels[i]) % labelcount
print(newlabels[6000])
nplabels = np.array(newlabels)
nplabels = tf.convert_to_tensor(nplabels)

['amp.TCP.reflection.SYNACK', 'pkt.TCP.synflood.spoofed', 'amp.UDP.manyprotocols', 'amp.UDP.snmp.src161', 'amp.UDP.UBNT.src10001', 'amp.dns.RRSIG.fragmented', 'amp.UDP.DNSANY', 'amp.TCP.syn.optionallyACK.optionallysamePort', 'amp.UDP.bacnet.IOT.37810', 'amp.UDP.memcached.ntp.cldap', 'pkt.UDP.rdm.fixedlength', 'pkt.ICMP.largeempty', 'pkt.TCP.DOMINATE.syn.ecn.cwr', 'amp.UDP.IOT.port37810.JSON', 'amp.UDP.isakmp']
lc:15
[54 6 0 0 80 47411]
0

In [8]:
#model = keras.Sequential()
#model.add(Conv2D([1,2,4,8,16,32,64], (6,1), name='conv0'))
#model.add(Dense(1, activation='sigmoid', name='fc1'))
# model.add(Activation('relu'))
# model.add(MaxPooling2D(pool_size=6, name='mp0'))
#model.compile(optimizer="rmsprop", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
model = keras.Sequential([
    layers.Dense(128, activation="relu"),
    #layers.MaxPooling2D(pool_size=6, name='mp0'),
    #layers.Dense(labelcount, activation='sigmoid', name='fc1'),
    layers.Dense(labelcount, activation="softmax")
])

In [9]:
model.compile(optimizer="rmsprop", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [10]:
model.fit(tensor, nplabels, epochs=4, steps_per_epoch=400)

Epoch 1/4
400/400 [==============================] - 1s 1ms/step - loss: 253.3746 - accuracy: 0.5443
Epoch 2/4
400/400 [==============================] - 1s 1ms/step - loss: 104.1118 - accuracy: 0.6460
Epoch 3/4
400/400 [==============================] - 1s 1ms/step - loss: 92.6423 - accuracy: 0.6781
Epoch 4/4
400/400 [==============================] - 1s 1ms/step - loss: 82.4585 - accuracy: 0.7028

In [11]:
predictions = model(tf.constant([[54, 6, 0, 0, 80, 10201]]))
#tf.print(predictions[0])
print(predictions[0])
print(uniquelabels[tf.argmax(predictions[0]).numpy()])

tf.Tensor([1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(15,), dtype=float32)
amp.TCP.reflection.SYNACK